# Generated by Django 2.2 on 2020-05-06 13:47

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('body', ckeditor.fields.RichTextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='date published')),
            ],
        ),
    ]
